---
title: "NASA Earthdata Cloud Cookbook"
subtitle: "Supporting NASA Earth Science Research Teams’ Migration to the Cloud" 
date: last-modified
author: "NASA Openscapes Team"
citation_url: https://nasa-openscapes.github.io/earthdata-cloud-cookbook/
slug: index
---

## Welcome

**Welcome to the NASA Openscapes Earthdata Cloud Cookbook!**

This Cookbook is learning-oriented to support scientific researchers who use NASA Earthdata as NASA migrates data and workflows to the cloud. It has resources to learn how to work with NASA Earthdata in the cloud, as well as documentation for how to contribute to these resources. It is under active, open development.

**Tip: use the _earthaccess_ Python library to access NASA Earthdata**. [earthaccess](https://earthaccess.readthedocs.io/en/latest/) is a Python library that streamlines access to NASA Earthdata locally or in the cloud. To learn more, see this [tech spotlight](https://nasa-openscapes.github.io/news/2024-03-04-earthaccess-tech-spotlight/), the [NASA Earthdata blog post](https://www.earthdata.nasa.gov/learn/blog/earthaccess), and these [how-to's](how-tos/find-data/find-python.html) and [tutorials](tutorials/). 

Looking for R and MATLAB help? See the [earthdatalogin R package](https://boettiger-lab.github.io/earthdatalogin/), and tutorials for [R](how-tos/find-data/find-r.html) and [MATLAB](tutorials/matlab.qmd) in this cookbook.

## About

This Earthdata Cloud Cookbook is being developed as a cross-DAAC collaboration by the NASA-Openscapes Team. Learn more at [nasa-openscapes.github.io](https://nasa-openscapes.github.io).

## Citation

Please cite the NASA Earthdata Cloud Cookbook through the project’s Zenodo archive using DOI: [10.5281/zenodo.7786710](https://doi.org/10.5281/zenodo.7786710). This DOI represents all versions, and will always resolve to the latest one.

The citation will look something like:

> Andy Barrett, Chris Battisto, Brandon Bottomley, Aaron Friesz, Alexis Hunzinger, Mahsa Jami, Alex Lewandowski, Bri Lind, Luis López, Jack McNelis, Cassie Nickles, Catalina Oaida Taglialatela, Celia Ou, Brianna Pagán, Sargent Shriver, Amy Steiker, Michele Thornton, Makhan Virdi, Jessica Nicole Welch, Jess Welch, Erin Robinson, Julia Stewart Lowndes. (2023). NASA-Openscapes/earthdata-cloud-cookbook: NASA EarthData Cloud Cookbook v2023.03.0 (v2023.03.0). Zenodo. https://doi.org/10.5281/zenodo.7786711

Please visit the Cookbook's [DOI link](https://doi.org/10.5281/zenodo.7786710) to get the most recent version - the one above is not automatically generated and may be out of date as we release updated versions of the Cookbook. 

## License

Openscapes makes all of their materials publicly available under open source licenses.

Our [License](LICENSE.md) is adapted from [The Turing Way](https://github.com/alan-turing-institute/the-turing-way/blob/master/LICENSE.md)

