---
title: Contributing
---

## How we work

The NASA Openscapes Mentor Community is collaborating to create this Cookbook, with an eye towards how others could collaborate with us in the future.

The [Openscapes Approach Guide](https://openscapes.github.io/approach-guide/approach/) describes how we work, including creating space and place, having a growth mindset, psychological safety, and continual learning, practice, and iteration. It also has our [code of conduct](https://openscapes.github.io/approach-guide/approach/code-of-conduct.html) and an overview of some of the workflows and tooling we use.

We believe open practices can accelerate data-driven solutions in science. These are critical to uncovering enduring science-based solutions faster, as well as for the well-being and resilience of research communities. We work towards kinder science.

Our style of working is greatly influenced by:

-   [The Turing Way Community Handbook](https://the-turing-way.netlify.app/community-handbook/community-handbook.html)
-   [The Carpentries Curriculum Development Handbook](https://carpentries.github.io/curriculum-development)
-   [The Documentation System](https://documentation.divio.com/) - by Daniele Procido/Divio; see image below!
-   [RStudio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/)
-   [eScience Hackweeks](https://guidebook.hackweek.io/intro.html)

The Earthdata Cloud Cookbook is made with [Quarto](https://quarto.org/) with our [2i2c](https://2i2c.org/) JupyterHub. Learn more in the [Setup](setup.qmd) and [Workflow](workflow.qmd) sections.

![Figure from documentation.divio.com: There is a secret that needs to be understood in order to write good software documentation: there isn\'t one thing called documentation, there are four. They are: tutorials, how-to guides, technical reference and explanation. They represent four different purposes or functions, and require four different approaches to their creation.](images/divio.png){fig-align="center" width="582"}

## Notebook templates

To help contributors get started quickly, we provide starter templates for new notebooks. Each template includes the standard front matter, section structure, and code patterns used across the Cookbook.

- [Python Jupyter Notebook Template](templates/notebook-template-python-jupyter.ipynb) - for `.ipynb` notebooks using Python
- [Python Quarto Template](templates/notebook-template-python-quarto.qmd) - for `.qmd` documents using Python
- [R Quarto Template](templates/notebook-template-r-quarto.qmd) - for `.qmd` documents using R

Copy the appropriate template into the relevant section of the Cookbook (e.g., `how-tos` or `tutorials`), and then edit it to add your content.
